### PR TITLE
bump dependencies for sycli

### PR DESCRIPTION
**Pull request by markpash**
As promised, this is a PR for updating some of the dependencies for sycli.

I've updated most of the dependencies for sycli except reqwest, which gave errors referring to error_chain and unimplemented methods. From what I can tell, error_chain is no longer advised and the community suggests moving to the failure crate. So I'll leave that for discussion and maybe another PR.

I also decided to drop the dependency on openssl and use the sha-1 crate.

And finally I noticed there were cargo lock files in the workspace members, and from what I have read, these aren't needed and the workspace lock file is used. So I removed the unused lock files and ran cargo update to update the workspace lock file.

### CODE REVIEW

**Review by kpcyrd — APPROVED** [review]

**Comment by Luminarys** [comment]
Thanks!

I think error handling across synapse in general is a bit messy, I experimented with multiple approaches, including error_chain in various modules. If you're willing to do some refactoring to switch things for Failure I'd be happy to accept the changes.

**Comment by evanrichter** [comment]
shouldn't the Cargo.lock be updated as well to ensure sycli doesn't break if dependencies break their semver commitments? I might be wrong, especially since this repo is a cargo workspace and I'm less familiar with how lock files are handled in this case

**Comment by Luminarys** [comment]
Hmm, it looks like the top level Cargo.lock has sycli's dependencies already.
I think the reason there were lock files before was from compiling in directory directly which shouldn't actually be needed.

**Comment by evanrichter** [comment]
ah that checks out, thanks for the explanation!

**Pull request merged**
