### PR TITLE
Fix deprecation warning

### PR DESCRIPTION
**Pull request by 95th**

### CODE REVIEW

**Comment by 95th** [comment]
It seems like min supported rust version is 1.30 but `MaybeUninit` was introduced in 1.36.. @Luminarys  can the min supported version be bumped up?

**Comment by Luminarys** [comment]
I think bumping up to 1.36 is a good idea now, thanks for the fix.

I am concerned about undefined behavior around MaybeUninit (though I'm pretty sure the current implementation is totally undefined but happens to work), specifically around `as_mut_ptr` being turned into a reference, [the docs](https://doc.rust-lang.org/beta/std/mem/union.MaybeUninit.html#method.as_mut_ptr) indicate this is UB.

Could you take a look at doing writes via pointers rather than references for the buffers?
If it's too much of a pain though I can give it a shot instead.

**Comment by 95th** [comment]
I haven't seen the whole flow yet but from previous usage of `mem::uninitialized` I assumed that the writes must be ordered before than read. If that's the case then this should work in similar way. But I admit that even so that is very brittle. Is the cost of initializing memory measurably high?

**Comment by Luminarys** [comment]
Writes must be ordered before reads, just the main issue is converting from a pointer to a reference before the write has gone through.

All things considered I don't think it's actually that much of a cost zeroing the memory, it just bugged me a lot at the time of writing the initial code which is why I chose to do it that way.
If you feel it's easier go ahead and make the buffer's zero initialized.

**Comment by 95th** [comment]
@Luminarys Updated. PTAL

**Comment by Luminarys** [comment]
Great, thanks!

**Pull request merged**
