### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by iamtakingithard**
Greetings, this PR adds GitHub Actions support.
Everything is built on Ubuntu 18.04. This was made to keep compatibility with my own seedbox. 

- Builds Debian package and synapse with sycli
- Caches the dependencies so you don't have to recompile/rebuild them from scratch
- Uploads the artifacts of deb package and synapse

### CODE REVIEW

**Comment by Luminarys** [comment]
Thanks for making these changes. I do agree that using Actions over Travis would probably be preferred longer term. Is there a way to test Actions before merging the PR?

**Comment by iamtakingithard** [comment]
You can just visit my repo, and take a look at Actions tab. Me myself uses these builds. But maybe you wanna get rid of sr.ht builds and Travis ones? Let me know what do you think

**Comment by Luminarys** [comment]
Thanks, that looks good!

**Comment by Luminarys** [comment]
I think we can remove the travis/sr.ht ones now as well, but that can be done in another PR.

**Pull request merged**
